spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/habittrackerdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: haslo1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
